language: ruby
env:
  - "RAILS_VERSION=3.2.13"
  - "RAILS_VERSION=4.0.0.pre"
rvm:
  - "1.9.3"
  - "2.0.0"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=4.0.0.pre"
    - rvm: 2.0.0
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script: rake db:migrate
