language: ruby
env:
  - "RAILS_VERSION=4.0.0"
rvm:
  - "2.0.0"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - rake db:migrate 
  - bundle exec rspec spec
after_script:
  - "bundle exec cucumber features"
