language: ruby
env:
  - "RAILS_VERSION=3.1.0"
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0.pre"
  - "RAILS_VERSION=master"
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
